### ISSUE TITLE
"The following capabilities could not be matched" when providing custom capabilities

### ISSUE THREAD

**Issue by bhecquet** [FlaUI/FlaUI.WebDriver#100]
Hello,

I'm using FlaUI webdriver to test windows applications and it works well when using it locally. Thank you for developping it!
I've tried to use it through selenium-grid and appium (using https://github.com/picakia/appium-flaui-driver) but I'm facing a problem. 
In the framework I'm using, some custom capabilities are attached to the selenium slot and these custom capabilities are transmitted to FlaUIDriver which complains about these capabilities.
How about just ignore capabilities that are not recognized by driver as it has no influence on how the driver get created ?

From my point of view, following lines could be removed

https://github.com/FlaUI/FlaUI.WebDriver/blob/e5d543b8b730e4051d425057dc2900941c507275/src/FlaUI.WebDriver/Controllers/SessionController.cs#L204C1-L207C14

**Comment by aristotelos** [comment]
Thank you for reporting, I am not sure whether this is a bug. The WebDriver specification seems to indicate that all capabilities should be matched, and that otherwise `null` should be returned. See https://www.w3.org/TR/webdriver2/#dfn-matching-capabilities

**Comment by bhecquet** [comment]
Hello @aristotelos, thanks for pointing the webdriver spec
In my use case, the custom capabilities are "extension capabilities" prefixed with "sr:". In that case, the specification states that: 

> Otherwise, if name is the key of an [extension capability](https://www.w3.org/TR/webdriver2/#dfn-extension-capability), let match value be the result of [trying](https://www.w3.org/TR/webdriver2/#dfn-try) implementation-specific steps to match on name with value. If the match is not successful, return [success](https://www.w3.org/TR/webdriver2/#dfn-success) with data [null](https://www.w3.org/TR/webdriver2/#dfn-null).

If I understand well, in that case, the driver should try to match (but it's not possible as it doesn't know these extension capabilities) so, it should return "success"

**Comment by aristotelos** [comment]
In this case "Return [success](https://www.w3.org/TR/webdriver2/#dfn-success) with data [null](https://www.w3.org/TR/webdriver2/#dfn-null)" for matching capabilities turns into an error when returning from the "create session" request, see https://www.w3.org/TR/webdriver2/#dfn-new-sessions:

> If capabilities's is [null](https://www.w3.org/TR/webdriver2/#dfn-null), return [error](https://www.w3.org/TR/webdriver2/#dfn-error) with [error code](https://www.w3.org/TR/webdriver2/#dfn-error-code) [session not created](https://www.w3.org/TR/webdriver2/#dfn-session-not-created).

**Comment by bhecquet** [comment]
Ok, i did not interpreted the specification correctly
However, what I can say, is that browser drivers do not care about extension capabilities

For example:
```java
ChromeOptions options = new ChromeOptions();
options.setCapability("foo:bar", "myValue");
WebDriver driver = new ChromeDriver(options);
driver.get("https://www.free.fr");
```
will start chrome without problem
