### ISSUE TITLE
How to verify desktop window in Minimized state or Maximized WindowVisualState

### ISSUE THREAD

**Issue by WeiweiCaiAcpt** [FlaUI/FlaUI.WebDriver#106]
We have a WPF application. When executing UI testing for it, we need to verify it is in Minimized or Maximized WindowVisualState.

We tried with below code to try get the window's visual state, but get "OpenQA.Selenium.WebDriverException: Only 'powerShell' scripts are supported" exception
`elemnt.GetAttribute("WindowVisualState")`

How can we use powerShell in GetAttribute() method?

**Comment by aristotelos** [comment]
In Selenium WebDriver, use `GetDomAttribute` because `GetAttribute` converts to javascript.

**Comment by WeiweiCaiAcpt** [comment]
@aristotelos  Thanks for looking into this issue.

I also tried with GetDomAttribute but it returns null.
Here is the FlaUInspect captured.
![image](https://github.com/user-attachments/assets/f21fc80d-fbb5-4bd2-85a7-1dac48f16acb)

And here is the code returned:
![image](https://github.com/user-attachments/assets/2a2c6fd9-4c38-4c00-ad12-6b7c830543e0)

It doesn't get error, but it doesn't get the WindowVisualState property value.

**Comment by aristotelos** [comment]
@WeiweiCaiAcpt Isn't this property part of the Window Pattern? In that case it has to be read with `GetDomAttribute("Window.WindowVisualState")`.

See README:

> Attributes with a period are treated as [Control Pattern Properties](https://learn.microsoft.com/en-us/windows/win32/winauto/uiauto-control-pattern-propids) with the form `Pattern.Property`.

**Comment by WeiweiCaiAcpt** [comment]
@aristotelos  Thanks for your help.

Yes, after switching to use "Window.WindowVisualState", we can get the Window Visual State now.
