### ISSUE TITLE
Appium: Providing .App throw's an error.

### ISSUE THREAD

**Issue by Dor-bl** [FlaUI/FlaUI.WebDriver#11]
Using Appium Dotntet client V5 RC

The below works for Microsoft/WinAppDriver
Error:

`OpenQA.Selenium.WebDriverArgumentException: 'Starting app 'Microsoft.WindowsCalculator_8wekyb3d8bbwe!App' with arguments '' threw an exception: An error occurred trying to start process 'Microsoft.WindowsCalculator_8wekyb3d8bbwe!App' with working directory '.'. The system cannot find the file specified.'`

Steps to repro:

        private WindowsDriver _calculatorSession;
        protected static WebElement CalculatorResult;
        private string _appId = "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App";

        [OneTimeSetUp]
        public void BeforeAll()
        {
            var appCapabilities = new AppiumOptions();
            appCapabilities.AutomationName = "Windows";
            appCapabilities.App = _appId;
            appCapabilities.DeviceName = "WindowsPC";
            appCapabilities.PlatformName = "Windows";

            var serverUri = Env.ServerIsRemote() ? AppiumServers.RemoteServerUri : AppiumServers.LocalServiceUri;
            _calculatorSession = new WindowsDriver(serverUri, appCapabilities,
                Env.InitTimeoutSec);
            _calculatorSession.Manage().Timeouts().ImplicitWait = Env.ImplicitTimeoutSec;

            _calculatorSession.FindElement(MobileBy.Name("Clear")).Click();
            _calculatorSession.FindElement(MobileBy.Name("Seven")).Click();
            CalculatorResult = _calculatorSession.FindElement(MobileBy.Name("Display is 7"));
            Assert.That(CalculatorResult, Is.Not.Null);
        }

**Comment by Dor-bl** [comment]
@aristotelos I assume this should be fixed under FlaUI core Library?

**Comment by aristotelos** [comment]
@Dor-bl This can probably be fixed in FlaUI.WebDriver by calling `Application.LaunchStoreApp`. Should FlaUI.WebDriver tell Windows Store Apps apart by a regular expression?

**Comment by aristotelos** [comment]
I've created a PR that looks if the appium:app ends with `!App` and if so, launches it as a Windows Store app.
