### ISSUE TITLE
Cannot combine control properties to locate element accurately

### ISSUE THREAD

**Issue by WeiweiCaiAcpt** [FlaUI/FlaUI.WebDriver#113]
When using FlaUI.WebDriver write UI testing, we found that if different element type has the same name, it cannot be located accurately.
For example, if there is a Label and a Textbox, both of them named "Phone Number". When use driver.FindElementByName(), both of them will be returned. So we have to use driver.FindElementsByName() to find both of them first. Then use index to select which element we want to operate.
```
var phones = driver.FindElementsByName("Phone Number");
phones[1].SendKeys("123456789");
```
In Coded UI, the logic of searching elements is combine the control's properties to locate it. If we want to find the Textbox, the Coded UI will use both Control Type and Name to find it.

Do you have any good idea for this scenario?

**Comment by aristotelos** [comment]
The recommended strategy to find elements is by automation ID (aka accessibility ID). This protects your tests against changes of text or localization differences. See https://github.com/appium/appium-windows-driver?tab=readme-ov-file#element-location and https://github.com/FlaUI/FlaUI.WebDriver?tab=readme-ov-file#selectors
