### ISSUE TITLE
DeviceName capability throws an exception

### ISSUE THREAD

**Issue by Dor-bl** [FlaUI/FlaUI.WebDriver#26]
When including DeviceName in the Appium Options, I receive the below error:
```
System.InvalidOperationException : Required capabilities did not match. Capability `platformName` with value `windows` is required, capability 'appium:automationName' with value `FlaUI` is required, and one of appium:app, appium:appTopLevelWindow or appium:appTopLevelWindowTitleMatch must be passed as a capability (SessionNotCreated)
```

Code to repro:
```
                    AppiumOptions desktopCapabilities = new AppiumOptions();
                    desktopCapabilities.App = "Root";
                    desktopCapabilities.DeviceName = "WindowsPC";
                    desktopCapabilities.AutomationName = "FlaUI";
                    var desktopSession = new WindowsDriver(serverUri, desktopCapabilities);
```

**Comment by aristotelos** [comment]
At the moment device name is not adding any information for the Windows automation, so it is not supported. Isn't it in that case expected to return that the capabilities do not match? 

What advantage would it have to support this capability?

**Comment by Dor-bl** [comment]
The error being thrown doesn't suggest there is an issue when providing deviceName, so you might want to address that anyway.
Other than that, there is no specific advantage to support this capability besides the fact existing Appium dotnet client tests use that capability, so in case I would like to migrate to FlaUI driver it will be less of a hassle.

**Comment by aristotelos** [comment]
I've created a pull request to improve the capability matching error messages.
