### ISSUE TITLE
FindElements returns NoSuchElement for 0 results.

### ISSUE THREAD

**Issue by grokys** [FlaUI/FlaUI.WebDriver#34]
As far as I can see from the spec, "Find Elements" should return an empty list if no matching elements were found:

https://www.w3.org/TR/webdriver2/#element-retrieval

> 7. Let result be an empty [List](https://www.w3.org/TR/webdriver2/#dfn-list).

> 8. For each element in elements returned, append the [web element reference object](https://www.w3.org/TR/webdriver2/#dfn-web-element-reference-object) for session and element, to result.

**Comment by aristotelos** [comment]
You are right, this should not be there for "Find elements", only for "Find element".
