### ISSUE TITLE
[Feat request] Support UseShellExecute & isAppOwnedBySession false

### ISSUE THREAD

**Issue by BrendanLester** [FlaUI/FlaUI.WebDriver#58]
This may need to be split in two if these settings are intended to be independently used.

I have an application which had a 'two-stage' start process. 

When I use standard FlaUI C# (non-WebDriver) I needed to use
- processStartInfo.UseShellExecute = true; 
- separate out Launch from Attach

e.g. 
```
var processStartInfo = new ProcessStartInfo("initialstart.application");
processStartInfo.UseShellExecute = true; 

using (Application.Launch(processStartInfo))
{
   Thread.Sleep(10000);	//wait for actual application to start
   using (var app = Application.Attach("actualapplication.exe"))
     {
```

These are not currently supported by WebDriver. For now, I have locally modified FlaUI.WebDriver SessionController.cs as
 ```
 processStartInfo.UseShellExecute = true;        //new line added here
 app = Core.Application.Launch(processStartInfo);
```

and 
`   isAppOwnedBySession = false;`

**Comment by aristotelos** [comment]
So you want to use two WebDriver sessions: One for launching "initialstart.application", which you want to keep running and not closed when the WebDriver session ends, and another one for launching "actualapplication.exe", which you want to end when the session ends? What is the role for `UseShellExecute` in this? Will the "initialstart.application" not start when you have `UseShellExecute` false?

I would suggest the following instead:

- Use a PowerShell script to start "intialstart.application"
- Then use a normal FlaUI.WebDriver session to start "actualapplication.exe"
