### ISSUE TITLE
Automate desktop

### ISSUE THREAD

**Issue by aplamon** [FlaUI/FlaUI.WebDriver#59]
We're using WinAppDriver atm and if you provide "Root" as app you can find the Taskbar and interact with the icons there. Is that not possible with FlaUI.WebDriver?

**Comment by aristotelos** [comment]
Launching as Root is possible, see also the README. Finding elements from the Root app is not yet supported (see https://github.com/FlaUI/FlaUI.WebDriver/blob/main/src/FlaUI.WebDriver/Session.cs#L48 that throws when you try to get the current window, which is used by the find elements controller), so I'll tag this as a feature request.
