### ISSUE TITLE
FlaUI with java

### ISSUE THREAD

**Issue by jonathangiber** [FlaUI/FlaUI.WebDriver#61]
Hi guys,
I successfully initialise a session with flaUI driver on root with java with following:

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("platformName", "windows");
capabilities.setCapability("appium:automationName", "flaui");
capabilities.setCapability("appium:app", "Root");
driver = new RemoteWebDriver(new URL("http://" + ip + ":4723/"), capabilities);

However, when I try to click on an element, I always get an exception such as "org.openqa.selenium.NoSuchWindowException: No windows are open for the current session" or similar. I successfully try java actions class with the driver and that is working as supposed but of course is very limited.
Any recommendations? 
Thanks

**Comment by daluu** [comment]
might be related to https://github.com/FlaUI/FlaUI.WebDriver/issues/59?

**Comment by aristotelos** [comment]
I agree that @daluu 's explanation sounds logical here.
