### ISSUE TITLE
Special characters aren't being sent correctly with sendKeys()

### ISSUE THREAD

**Issue by jonathangiber** [FlaUI/FlaUI.WebDriver#77]
Special characters arent being sent right with sendKeys(), for example, when trying to send "@", value "2" is sent instead.
To make it work for now Im using the following:

/
```java
actions.keyDown(Keys.SHIFT).sendKeys("2").keyUp(Keys.SHIFT).build().perform();
```

**Comment by aristotelos** [comment]
@jonathangiber Thanks for reporting. I have added some UI tests but cannot reproduce what you say. See https://github.com/FlaUI/FlaUI.WebDriver/pull/79

**Comment by jonathangiber** [comment]
This could be related to the fact I was using java class Actions since before the latest flaUI version, I couldn't properly find elements in the desktop. Will use the driver only now, thanks.
