### ISSUE TITLE
Sending keys `<` or `>` results in `|`

### ISSUE THREAD

**Issue by bmarroquin** [FlaUI/FlaUI.WebDriver#91]
This is a problem with the spec version 2 more than a problem with the implementation here. See https://github.com/w3c/webdriver/issues/1841. 

Explanation of why this happens:
* It looks like the spec defined IntlBackslash as `<` and `>` (Shifted) instead of `\` and `|`(shifted).
* `<` is defined as both a shifted and not shifted char. Since the implementation determines it is shifted and checks the non-shifted code table first this results in a Shifted IntlBackslash or `|`
  * Checking the shifted table first would fix this, but then it would prevent using the non-shifted version of  `<`.
* `>` is the shifted version of `<` which results in a Shifted IntlBackslash or `|`

[Spec version 1](https://www.w3.org/TR/webdriver1/#keyboard-actions) has `>` mapped as the shifted version of `.`.  If we added that and check the shifted table first, everything should work fine. The IntlBackslash is still wrong here though.

**Comment by bmarroquin** [comment]
Ah, this also impacts trying to type `.`. `.` is both a shifted and not shifted char. This results in an action sequence of shifted `.` which always prints `>`.

**Comment by lagori** [comment]
I had the same issue of . yesterday the work around for this is to use the actions class.
Actions actions = new Actions(driver);
        actions.MoveToElement(uname)
               .Click()
               .SendKeys("test.user1")
               .Perform();
